version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/my-color-app
    ports:
      - 5173:5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
